#!/usr/bin/perl

print "Content-type: text/html", "\n\n";

print "<HTML>", "\n";
print "<HEAD><TITLE>Informacio&acuten sobre este servidor</TITLE></HEAD>",
"\n";
print "<HR><PRE>";
print "Nombre del servidor:	", $ENV{'SERVER_NAME'}, "<BR>", "\n";
print "Corre en el puerto:	", $ENV{'SERVER_PORT'}, "<BR>", "\n";
print "Software del servidor:	", $ENV{'SERVER_SOFTWARE'}, "<BR>", "\n";
print "Protocolo del servidor:	", $ENV{'SERVER_PROTOCOL'}, "<BR>", "\n";
print "Version de CGI:		", $ENV{'GATEWAY_INTERFACE'}, "<BR>", "\n";
print "<HR></PRE>", "\n";
print "</BODY></HTML>", "\n";
exit (0);